/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ProfilRouteImport } from './routes/profil'
import { Route as KontakRouteImport } from './routes/kontak'
import { Route as GaleriRouteImport } from './routes/galeri'
import { Route as BeritaRouteImport } from './routes/berita'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BeritaSlugRouteImport } from './routes/berita.$slug'
import { Route as AuthenticatedOperatorRouteImport } from './routes/_authenticated/operator'
import { Route as AuthenticatedAnggotaRouteImport } from './routes/_authenticated/anggota'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedAnggotaProfilRouteImport } from './routes/_authenticated/anggota.profil'
import { Route as AuthenticatedAdminBeritaRouteImport } from './routes/_authenticated/admin.berita'
import { Route as AuthenticatedAdminAnggotaRouteImport } from './routes/_authenticated/admin.anggota'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfilRoute = ProfilRouteImport.update({
  id: '/profil',
  path: '/profil',
  getParentRoute: () => rootRouteImport,
} as any)
const KontakRoute = KontakRouteImport.update({
  id: '/kontak',
  path: '/kontak',
  getParentRoute: () => rootRouteImport,
} as any)
const GaleriRoute = GaleriRouteImport.update({
  id: '/galeri',
  path: '/galeri',
  getParentRoute: () => rootRouteImport,
} as any)
const BeritaRoute = BeritaRouteImport.update({
  id: '/berita',
  path: '/berita',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BeritaSlugRoute = BeritaSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BeritaRoute,
} as any)
const AuthenticatedOperatorRoute = AuthenticatedOperatorRouteImport.update({
  id: '/operator',
  path: '/operator',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAnggotaRoute = AuthenticatedAnggotaRouteImport.update({
  id: '/anggota',
  path: '/anggota',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAnggotaProfilRoute =
  AuthenticatedAnggotaProfilRouteImport.update({
    id: '/profil',
    path: '/profil',
    getParentRoute: () => AuthenticatedAnggotaRoute,
  } as any)
const AuthenticatedAdminBeritaRoute =
  AuthenticatedAdminBeritaRouteImport.update({
    id: '/berita',
    path: '/berita',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminAnggotaRoute =
  AuthenticatedAdminAnggotaRouteImport.update({
    id: '/anggota',
    path: '/anggota',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/berita': typeof BeritaRouteWithChildren
  '/galeri': typeof GaleriRoute
  '/kontak': typeof KontakRoute
  '/profil': typeof ProfilRoute
  '/reset-password': typeof ResetPasswordRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/anggota': typeof AuthenticatedAnggotaRouteWithChildren
  '/operator': typeof AuthenticatedOperatorRoute
  '/berita/$slug': typeof BeritaSlugRoute
  '/admin/anggota': typeof AuthenticatedAdminAnggotaRoute
  '/admin/berita': typeof AuthenticatedAdminBeritaRoute
  '/anggota/profil': typeof AuthenticatedAnggotaProfilRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/berita': typeof BeritaRouteWithChildren
  '/galeri': typeof GaleriRoute
  '/kontak': typeof KontakRoute
  '/profil': typeof ProfilRoute
  '/reset-password': typeof ResetPasswordRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/anggota': typeof AuthenticatedAnggotaRouteWithChildren
  '/operator': typeof AuthenticatedOperatorRoute
  '/berita/$slug': typeof BeritaSlugRoute
  '/admin/anggota': typeof AuthenticatedAdminAnggotaRoute
  '/admin/berita': typeof AuthenticatedAdminBeritaRoute
  '/anggota/profil': typeof AuthenticatedAnggotaProfilRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/berita': typeof BeritaRouteWithChildren
  '/galeri': typeof GaleriRoute
  '/kontak': typeof KontakRoute
  '/profil': typeof ProfilRoute
  '/reset-password': typeof ResetPasswordRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/anggota': typeof AuthenticatedAnggotaRouteWithChildren
  '/_authenticated/operator': typeof AuthenticatedOperatorRoute
  '/berita/$slug': typeof BeritaSlugRoute
  '/_authenticated/admin/anggota': typeof AuthenticatedAdminAnggotaRoute
  '/_authenticated/admin/berita': typeof AuthenticatedAdminBeritaRoute
  '/_authenticated/anggota/profil': typeof AuthenticatedAnggotaProfilRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/berita'
    | '/galeri'
    | '/kontak'
    | '/profil'
    | '/reset-password'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/admin'
    | '/anggota'
    | '/operator'
    | '/berita/$slug'
    | '/admin/anggota'
    | '/admin/berita'
    | '/anggota/profil'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/berita'
    | '/galeri'
    | '/kontak'
    | '/profil'
    | '/reset-password'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/admin'
    | '/anggota'
    | '/operator'
    | '/berita/$slug'
    | '/admin/anggota'
    | '/admin/berita'
    | '/anggota/profil'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/berita'
    | '/galeri'
    | '/kontak'
    | '/profil'
    | '/reset-password'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/_authenticated/admin'
    | '/_authenticated/anggota'
    | '/_authenticated/operator'
    | '/berita/$slug'
    | '/_authenticated/admin/anggota'
    | '/_authenticated/admin/berita'
    | '/_authenticated/anggota/profil'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  BeritaRoute: typeof BeritaRouteWithChildren
  GaleriRoute: typeof GaleriRoute
  KontakRoute: typeof KontakRoute
  ProfilRoute: typeof ProfilRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profil': {
      id: '/profil'
      path: '/profil'
      fullPath: '/profil'
      preLoaderRoute: typeof ProfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kontak': {
      id: '/kontak'
      path: '/kontak'
      fullPath: '/kontak'
      preLoaderRoute: typeof KontakRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/galeri': {
      id: '/galeri'
      path: '/galeri'
      fullPath: '/galeri'
      preLoaderRoute: typeof GaleriRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/berita': {
      id: '/berita'
      path: '/berita'
      fullPath: '/berita'
      preLoaderRoute: typeof BeritaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/berita/$slug': {
      id: '/berita/$slug'
      path: '/$slug'
      fullPath: '/berita/$slug'
      preLoaderRoute: typeof BeritaSlugRouteImport
      parentRoute: typeof BeritaRoute
    }
    '/_authenticated/operator': {
      id: '/_authenticated/operator'
      path: '/operator'
      fullPath: '/operator'
      preLoaderRoute: typeof AuthenticatedOperatorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/anggota': {
      id: '/_authenticated/anggota'
      path: '/anggota'
      fullPath: '/anggota'
      preLoaderRoute: typeof AuthenticatedAnggotaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/anggota/profil': {
      id: '/_authenticated/anggota/profil'
      path: '/profil'
      fullPath: '/anggota/profil'
      preLoaderRoute: typeof AuthenticatedAnggotaProfilRouteImport
      parentRoute: typeof AuthenticatedAnggotaRoute
    }
    '/_authenticated/admin/berita': {
      id: '/_authenticated/admin/berita'
      path: '/berita'
      fullPath: '/admin/berita'
      preLoaderRoute: typeof AuthenticatedAdminBeritaRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/anggota': {
      id: '/_authenticated/admin/anggota'
      path: '/anggota'
      fullPath: '/admin/anggota'
      preLoaderRoute: typeof AuthenticatedAdminAnggotaRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminAnggotaRoute: typeof AuthenticatedAdminAnggotaRoute
  AuthenticatedAdminBeritaRoute: typeof AuthenticatedAdminBeritaRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminAnggotaRoute: AuthenticatedAdminAnggotaRoute,
  AuthenticatedAdminBeritaRoute: AuthenticatedAdminBeritaRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedAnggotaRouteChildren {
  AuthenticatedAnggotaProfilRoute: typeof AuthenticatedAnggotaProfilRoute
}

const AuthenticatedAnggotaRouteChildren: AuthenticatedAnggotaRouteChildren = {
  AuthenticatedAnggotaProfilRoute: AuthenticatedAnggotaProfilRoute,
}

const AuthenticatedAnggotaRouteWithChildren =
  AuthenticatedAnggotaRoute._addFileChildren(AuthenticatedAnggotaRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedAnggotaRoute: typeof AuthenticatedAnggotaRouteWithChildren
  AuthenticatedOperatorRoute: typeof AuthenticatedOperatorRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedAnggotaRoute: AuthenticatedAnggotaRouteWithChildren,
  AuthenticatedOperatorRoute: AuthenticatedOperatorRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface BeritaRouteChildren {
  BeritaSlugRoute: typeof BeritaSlugRoute
}

const BeritaRouteChildren: BeritaRouteChildren = {
  BeritaSlugRoute: BeritaSlugRoute,
}

const BeritaRouteWithChildren =
  BeritaRoute._addFileChildren(BeritaRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  BeritaRoute: BeritaRouteWithChildren,
  GaleriRoute: GaleriRoute,
  KontakRoute: KontakRoute,
  ProfilRoute: ProfilRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.tsx'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
